[toolchain]

[features]
seeds = false
skip-lint = false

[workspace]
members = ["programs/*"]

[programs.testnet]
agent_factory = "4m6mpe2jdRiM24ui1Z3AGbCheu1DfQEjmEGtaGKD2ftU"

[programs.devnet]
agent_factory = "4m6mpe2jdRiM24ui1Z3AGbCheu1DfQEjmEGtaGKD2ftU"

[programs.localnet]
agent_factory = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "testnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

